DELIMITER $$
DROP PROCEDURE IF EXISTS client_data $$
CREATE PROCEDURE client_data()
BEGIN
    START TRANSACTION;
		CREATE TABLE ClientData (
			ClientID SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
			Name VARCHAR(100) NOT NULL,
			Address VARCHAR(255) NOT NULL,
			PhoneNumber VARCHAR(20) NOT NULL
		);
    END $$
DELIMITER ;
CALL client_data();